In [29]:
''''Random forests is a supervised learning algorithm. It can be used both for classification and regression. 
It is also the most flexible and easy to use algorithm. A forest is comprised of trees. It is said that the more 
trees it has, the more robust a forest is. Random forests creates decision trees on randomly selected data samples, 
gets prediction from each tree and selects the best solution by means of voting. It also provides a pretty good indicator 
of the feature importance.

It works in four steps:

*Select random samples from a given dataset.
*Construct a decision tree for each sample and get a prediction result from each decision tree.
*Perform a vote for each predicted result.
*Select the prediction result with the most votes as the final prediction.
................................................
Advantages: Random forests is considered as a highly accurate and robust method because of the number of decision trees 
            participating in the process.
            It does not suffer from the overfitting problem. The main reason is that it takes the average of all the 
            predictions, which cancels out the biases.
            The algorithm can be used in both classification and regression problems.
            Random forests can also handle missing values. (There are two ways to handle these: using median values to replace 
            continuous variables, and computing the proximity-weighted average of missing values.) 
            we can get the relative feature importance, which helps in selecting the most contributing features for the 
            classifier.
Disadvantages: Random forests is slow in generating predictions because it has multiple decision trees. Whenever it makes a
               prediction, all the trees in the forest have to make a prediction for the same given input and then perform 
               voting on it. This whole process is time-consuming.
              The model is difficult to interpret compared to a decision tree, where you can easily make a decision by 
              following the path in the tree
...............................................
compair to other '''

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-29-1619602cebeb>, line 29)

In [30]:
#importing libraries
import os
import pandas as pd
import numpy as np

In [31]:
#open the dataset files and list the directories available in that dataset file
path="C:\\Users\\best\\Downloads\\Earthquake_damage\\Earthquake_damage"
print(os.listdir(path))

['Building_Ownership_Use.csv', 'Building_Structure.csv', 'ReadMe.md', 'sample_submission.csv', 'test.csv', 'train.csv']


In [32]:
#open the csv file ,take first 10000 data from total data.pd.read_csv is used to read the csv file and do operations on it
training=pd.read_csv(path+'\\train.csv')      
training.head()
data1=training[:20000]

In [33]:
data2=pd.read_csv(path+'\\Building_Ownership_Use.csv')
data2.head()
data3 = pd.merge(data2,data1,on=['building_id'])

In [34]:
data4=pd.read_csv(path+'\\Building_Structure.csv')
data4.head()
data= pd.merge(data4,data3,on=['building_id'])

In [35]:
#list the what are the featuers consider for training
features=list(data)
print(features)

['building_id', 'district_id', 'vdcmun_id', 'ward_id_x', 'count_floors_pre_eq', 'count_floors_post_eq', 'age_building', 'plinth_area_sq_ft', 'height_ft_pre_eq', 'height_ft_post_eq', 'land_surface_condition', 'foundation_type', 'roof_type', 'ground_floor_type', 'other_floor_type', 'position', 'plan_configuration', 'has_superstructure_adobe_mud', 'has_superstructure_mud_mortar_stone', 'has_superstructure_stone_flag', 'has_superstructure_cement_mortar_stone', 'has_superstructure_mud_mortar_brick', 'has_superstructure_cement_mortar_brick', 'has_superstructure_timber', 'has_superstructure_bamboo', 'has_superstructure_rc_non_engineered', 'has_superstructure_rc_engineered', 'has_superstructure_other', 'condition_post_eq', 'district_id_x', 'vdcmun_id_x', 'ward_id_y', 'legal_ownership_status', 'count_families', 'has_secondary_use', 'has_secondary_use_agriculture', 'has_secondary_use_hotel', 'has_secondary_use_rental', 'has_secondary_use_institution', 'has_secondary_use_school', 'has_secondary_u

In [36]:
#creating a dictionary for storing the  numeric value of corresponding string 
dictionary={}
i=0

In [37]:
#convertion is a function used to convert the string values in to numeric value ,where we take word is the key,
def convertion(dictionary,word):
    if word not in dictionary:
        value=len(dictionary)
        dictionary[word]=value
        return dictionary[word]
    else:
        return dictionary[word]

In [38]:
#go through each cell ,that cell contain value stored into variable word.then find the datatype of each cell values ,
#if it is objective then call convertion function.then we get the neumeric value corresponding object.then it consider the new
#new value of the that perticular cell
i=0
for i in range(len(data)):
    for feature in features:
        word=data.loc[i,feature]
        if data[feature].dtype==object:
            convertion(dictionary,word)
            new_data=dictionary[word]
            data.loc[i,feature]=new_data

In [39]:
#from the dataset any cell is empty then it replace with 0
data.fillna(0,inplace=True)

In [40]:
#we create two class with or without grade.so that in x contain dataset without grade and y contain with label.for 
#training purpose we make this category
x = data.drop('damage_grade', axis=1)
y = data['damage_grade']


In [41]:
#we want training and testing dataset for that we splite the available dataset by using train_test_split.spliting done with 80% training 20% for testing
from sklearn.model_selection import train_test_split
x_Train, x_Test, y_Train, y_Test = train_test_split(x, y, test_size = 0.2,train_size=0.8)

In [50]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=300)


In [51]:

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_Train,y_Train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [52]:
y_pred=clf.predict(x_Test)

In [53]:
#At this point we have trained our algorithm and made some predictions. Now we'll see how accurate our algorithm is. 
#For classification tasks some commonly used metrics are confusion matrix, precision, recall, and F1 score. 
#Lucky for us Scikit=-Learn's metrics library contains the classification_report and confusion_matrix methods that can be used 
#to calculate these metrics for us:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_Test, y_pred))
print(classification_report(y_Test, y_pred))

[[ 346  138    0  264    2]
 [ 192  264    0   82    5]
 [   7    2 1272   69    0]
 [ 189   54    4  683    1]
 [  28   49    0    4  345]]
              precision    recall  f1-score   support

          11       0.45      0.46      0.46       750
          17       0.52      0.49      0.50       543
          27       1.00      0.94      0.97      1350
          30       0.62      0.73      0.67       931
          35       0.98      0.81      0.89       426

    accuracy                           0.73      4000
   macro avg       0.71      0.69      0.70      4000
weighted avg       0.74      0.73      0.73      4000

